language: c

env:
  global:
    - GAP_BOOTSTRAP=minimal
    - GAP_PKGS_TO_CLONE="json io profiling"
    - GAP_PKGS_TO_BUILD="json io profiling"

branches:
  except:
    - gh-pages

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev
    - texlive-latex-extra
    - texlive-fonts-recommended

matrix:
  include:
    - env: GAPBRANCH="stable-4.11"
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: ABI=32
      addons:
        apt_packages:
          - libcurl4-openssl-dev:i386
          - libgmp-dev:i386
          - libreadline-dev:i386
          - texlive-latex-extra:i386
          - texlive-fonts-recommended:i386
          - gcc-multilib
          - g++-multilib

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
